TEXTS = {
    "tr": {
        "welcome_new": "Hoş geldin, <b>{name}</b>! 👋\n\n💰 Bakiyen: <b>{credits} kredi</b>\n\nNe yapmak istersin?",
        "welcome_back": "Tekrar hoş geldin, <b>{name}</b>! 👋\n\n💰 Bakiyen: <b>{credits} kredi</b>\n\nNe yapmak istersin?",
        "no_credits": "Tekrar hoş geldin, <b>{name}</b>! 👋\n\n😔 <b>0 kredin</b> kaldı.\nGörseller oluşturmaya devam etmek için bakiyeni yükselt.",
        "choose_model": "Modelini seç:",
        "choose_quality": "Kaliteyi seç:",
        "choose_ratio": "En-boy oranını seç:",
        "prompt_cost": "✏️ Promptunu yaz.\n💰 Bu işlem <b>{cost} kredi</b> tutacak.",
        "ask_image": "📎 İsterseniz bir referans fotoğraf gönderin, ardından promptunuzu yazın.\nSadece metin göndermek için promptunuzu doğrudan yazabilirsiniz.\n💰 Bu işlem <b>{cost} kredi</b> tutacak.",
        "image_received": "✅ Fotoğraf alındı! Şimdi promptunuzu yazın:",
        "skip_image": "⏭️ Fotoğrafsız devam et",
        "uploading_image": "📤 Fotoğraf yükleniyor...",
        "generating": "⏳ Görseliniz oluşturuluyor, lütfen bekleyin...",
        "done": "✅ <b>Tamamlandı!</b>\n<b>Model:</b> {model}\n<b>Kalite:</b> {quality}\n<b>Oran:</b> {ratio}\n\n💰 Harcanan: <b>{cost} kredi</b> | Kalan: <b>{balance} kredi</b>",
        "no_credits_gen": "❌ <b>Yetersiz kredi!</b>\n\nBu işlem <b>{cost} kredi</b> tutar.\nBakiyen: <b>{balance} kredi</b>.\n\nLütfen bakiyeni yükselt.",
        "gen_failed": "❌ Oluşturma başarısız: {error}\n\nTekrar denemek için /start",
        "balance_msg": "💳 <b>Bakiyen</b>\n\nKalan kredi: <b>{credits}</b>\n\nPaket seç:",
        "payment_success": "✅ <b>Ödeme başarılı!</b>\n\nEklendi: <b>{credits} kredi</b>\nYeni bakiye: <b>{balance} kredi</b>\n\n🎨 Oluşturmaya başlamak için /start",
        "lang_changed": "🇹🇷 Dil Türkçe olarak ayarlandı.",
        "choose_language": "🌍 Dil seç:",
        "btn_generate": "🎨 Görsel Oluştur",
        "btn_balance": "💳 Bakiye & Yükselt",
        "btn_repeat": "🔁 Tekrar Oluştur",
        "btn_restart": "🔄 Baştan Başla",
        "btn_show_balance": "💳 Bakiyemi Gör",
        "btn_add_credits": "➕ Kredi Yükle",
        "btn_lang": "🌍 Dil Değiştir",
    },
    "en": {
        "welcome_new": "Welcome, <b>{name}</b>! 👋\n\n💰 Your balance: <b>{credits} credits</b>\n\nWhat would you like to do?",
        "welcome_back": "Welcome back, <b>{name}</b>! 👋\n\n💰 Your balance: <b>{credits} credits</b>\n\nWhat would you like to do?",
        "no_credits": "Welcome back, <b>{name}</b>! 👋\n\n😔 You have <b>0 credits</b> left.\nTop up your balance to continue generating images.",
        "choose_model": "Choose your model:",
        "choose_quality": "Choose quality:",
        "choose_ratio": "Choose aspect ratio:",
        "prompt_cost": "✏️ Write your prompt.\n💰 This generation will cost <b>{cost} credits</b>.",
        "ask_image": "📎 Optionally send a reference photo, then write your prompt.\nOr just type your prompt directly to skip the image.\n💰 This generation will cost <b>{cost} credits</b>.",
        "image_received": "✅ Photo received! Now write your prompt:",
        "skip_image": "⏭️ Continue without photo",
        "uploading_image": "📤 Uploading photo...",
        "generating": "⏳ Generating your image, please wait...",
        "done": "✅ <b>Done!</b>\n<b>Model:</b> {model}\n<b>Quality:</b> {quality}\n<b>Ratio:</b> {ratio}\n\n💰 Spent: <b>{cost} credits</b> | Remaining: <b>{balance} credits</b>",
        "no_credits_gen": "❌ <b>Insufficient credits!</b>\n\nThis generation costs <b>{cost} credits</b>.\nYour balance: <b>{balance} credits</b>.\n\nPlease top up your balance.",
        "gen_failed": "❌ Generation failed: {error}\n\nTry again with /start",
        "balance_msg": "💳 <b>Your Balance</b>\n\nCredits remaining: <b>{credits}</b>\n\nChoose a package:",
        "payment_success": "✅ <b>Payment successful!</b>\n\nAdded: <b>{credits} credits</b>\nNew balance: <b>{balance} credits</b>\n\n🎨 Start generating with /start",
        "lang_changed": "🇬🇧 Language set to English.",
        "choose_language": "🌍 Choose language:",
        "btn_generate": "🎨 Image Generation",
        "btn_balance": "💳 Balance & Top Up",
        "btn_repeat": "🔁 Repeat Prompt",
        "btn_restart": "🔄 Start Over",
        "btn_show_balance": "💳 My Balance",
        "btn_add_credits": "➕ Add Credits",
        "btn_lang": "🌍 Change Language",
    },
    "ru": {
        "welcome_new": "Добро пожаловать, <b>{name}</b>! 👋\n\n💰 Ваш баланс: <b>{credits} кредитов</b>\n\nЧто хотите сделать?",
        "welcome_back": "С возвращением, <b>{name}</b>! 👋\n\n💰 Ваш баланс: <b>{credits} кредитов</b>\n\nЧто хотите сделать?",
        "no_credits": "С возвращением, <b>{name}</b>! 👋\n\n😔 У вас осталось <b>0 кредитов</b>.\nПополните баланс для продолжения.",
        "choose_model": "Выберите модель:",
        "choose_quality": "Выберите качество:",
        "choose_ratio": "Выберите соотношение сторон:",
        "prompt_cost": "✏️ Напишите ваш запрос.\n💰 Эта генерация будет стоить <b>{cost} кредитов</b>.",
        "ask_image": "📎 Отправьте референс-фото (необязательно), затем напишите запрос.\nИли просто напишите запрос без фото.\n💰 Стоимость: <b>{cost} кредитов</b>.",
        "image_received": "✅ Фото получено! Теперь напишите запрос:",
        "skip_image": "⏭️ Продолжить без фото",
        "uploading_image": "📤 Загрузка фото...",
        "generating": "⏳ Генерация изображения, подождите...",
        "done": "✅ <b>Готово!</b>\n<b>Модель:</b> {model}\n<b>Качество:</b> {quality}\n<b>Соотношение:</b> {ratio}\n\n💰 Потрачено: <b>{cost} кр.</b> | Остаток: <b>{balance} кр.</b>",
        "no_credits_gen": "❌ <b>Недостаточно кредитов!</b>\n\nГенерация стоит <b>{cost} кредитов</b>.\nВаш баланс: <b>{balance} кредитов</b>.\n\nПополните баланс.",
        "gen_failed": "❌ Ошибка генерации: {error}\n\nПопробуйте снова /start",
        "balance_msg": "💳 <b>Ваш баланс</b>\n\nОстаток кредитов: <b>{credits}</b>\n\nВыберите пакет:",
        "payment_success": "✅ <b>Оплата успешна!</b>\n\nДобавлено: <b>{credits} кредитов</b>\nНовый баланс: <b>{balance} кредитов</b>\n\n🎨 Начать генерацию: /start",
        "lang_changed": "🇷🇺 Язык изменён на русский.",
        "choose_language": "🌍 Выберите язык:",
        "btn_generate": "🎨 Создать изображение",
        "btn_balance": "💳 Баланс и пополнение",
        "btn_repeat": "🔁 Повторить",
        "btn_restart": "🔄 Начать заново",
        "btn_show_balance": "💳 Мой баланс",
        "btn_add_credits": "➕ Пополнить",
        "btn_lang": "🌍 Сменить язык",
    },
    "fa": {
        "welcome_new": "خوش آمدی، <b>{name}</b>! 👋\n\n💰 موجودی شما: <b>{credits} اعتبار</b>\n\nچه کاری می‌خواهید انجام دهید؟",
        "welcome_back": "خوش برگشتی، <b>{name}</b>! 👋\n\n💰 موجودی شما: <b>{credits} اعتبار</b>\n\nچه کاری می‌خواهید انجام دهید؟",
        "no_credits": "خوش برگشتی، <b>{name}</b>! 👋\n\n😔 <b>0 اعتبار</b> باقی مانده.\nبرای ادامه تولید تصویر، موجودی خود را شارژ کنید.",
        "choose_model": "مدل را انتخاب کنید:",
        "choose_quality": "کیفیت را انتخاب کنید:",
        "choose_ratio": "نسبت تصویر را انتخاب کنید:",
        "prompt_cost": "✏️ دستور خود را بنویسید.\n💰 این تولید <b>{cost} اعتبار</b> هزینه دارد.",
        "ask_image": "📎 می‌توانید یک عکس مرجع ارسال کنید، سپس دستور بنویسید.\nیا مستقیماً دستور خود را بنویسید.\n💰 هزینه: <b>{cost} اعتبار</b>.",
        "image_received": "✅ عکس دریافت شد! حالا دستور خود را بنویسید:",
        "skip_image": "⏭️ ادامه بدون عکس",
        "uploading_image": "📤 در حال آپلود عکس...",
        "generating": "⏳ در حال تولید تصویر، لطفاً صبر کنید...",
        "done": "✅ <b>انجام شد!</b>\n<b>مدل:</b> {model}\n<b>کیفیت:</b> {quality}\n<b>نسبت:</b> {ratio}\n\n💰 مصرف شده: <b>{cost} اعتبار</b> | باقی‌مانده: <b>{balance} اعتبار</b>",
        "no_credits_gen": "❌ <b>اعتبار کافی نیست!</b>\n\nاین تولید <b>{cost} اعتبار</b> هزینه دارد.\nموجودی شما: <b>{balance} اعتبار</b>.\n\nلطفاً موجودی خود را شارژ کنید.",
        "gen_failed": "❌ خطا در تولید: {error}\n\nبرای تلاش مجدد /start",
        "balance_msg": "💳 <b>موجودی شما</b>\n\nاعتبار باقی‌مانده: <b>{credits}</b>\n\nبسته را انتخاب کنید:",
        "payment_success": "✅ <b>پرداخت موفق!</b>\n\nاضافه شد: <b>{credits} اعتبار</b>\nموجودی جدید: <b>{balance} اعتبار</b>\n\n🎨 برای شروع: /start",
        "lang_changed": "☀️🦁 زبان به فارسی تغییر یافت.",
        "choose_language": "🌍 زبان را انتخاب کنید:",
        "btn_generate": "🎨 تولید تصویر",
        "btn_balance": "💳 موجودی و شارژ",
        "btn_repeat": "🔁 تکرار",
        "btn_restart": "🔄 شروع مجدد",
        "btn_show_balance": "💳 موجودی من",
        "btn_add_credits": "➕ شارژ اعتبار",
        "btn_lang": "🌍 تغییر زبان",
    },
}

def t(lang: str, key: str, **kwargs) -> str:
    text = TEXTS.get(lang, TEXTS["tr"]).get(key, TEXTS["tr"].get(key, key))
    return text.format(**kwargs) if kwargs else text